id: P000726
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W28737
  title: རྗེ་བཙུན་བླ་མ་དམ་པ་ངག་དབང་ཆོས་འཕེལ་བཟང་པོའི་རྣམ་ཐར
  author: ''
  volumes:
    4989af533ac94e2c87ff9fc7dc6683fe:
      image_group_id: I1GS105460
      title: ''
      volume_number: 1
      total_pages: 114
      base_file: v001.txt
